name: "[rollup-boost] Builder Playground Integration Tests"

on:
  # Allow manual trigger
  workflow_dispatch:
  # Run nightly at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: Run Builder Playground Integration Tests
    runs-on: warp-ubuntu-latest-x64-16x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Build Rollup boost image
        run: |
          just build

      - name: Run rollup-boost with builder-playground
        uses: flashbots/builder-playground-action@v1
        with:
          version: v0.3.2-alpha.7
          recipe: playground.yaml
          args: --skip-setup

      - name: Send test tx to the builder
        run: builder-playground test http://localhost:8547 --timeout 30s --retries 10
